---

- name: install docker
  yum: 
    name: "{{ item }}"

    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes

- name: install docker-compose
  pip:
    name:
      - setuptools
      - docker-compose
    executable: pip3
  ignore_errors: yes


